show_description: 
  default: true
  description: 'Show description from "About This Category" post'

show_mobile: 
  default: true
  description: 'Show banners on mobile'

show_subcategory: 
  default: true
  description: 'Show banners for subcategories'

hide_if_no_description: 
  default: true
  description: 'Hide banners if category description is not set'

exceptions:
  default: ""
  type: list
  description: "Banner will not show for these categories"

categories:
  default: ""
  type: list
  description: |
    Banner will only show for these categories. Format: name:target.
    *targets* all: Named category and subcategories;
              no_sub: Only the named category;
              only_sub: Only subcategories of the named category;